import {describe,it,expect,vi} from 'vitest';
import {assets,board,candidates,dates,freshness,providers,readAdapter,safeLink,selectNews,tradingView,type BoardRow,type Candidate,type NewsItem} from '../src/data';
import {indicators,score} from '../src/domain';
describe('rights, links and independent publication',()=>{
 it('does not invoke adapter without explicit fetch AND display rights',async()=>{const load=vi.fn();await expect(readAdapter({policy:providers[0],load},dates[0])).rejects.toThrow('rights unknown');expect(load).not.toHaveBeenCalled();await expect(readAdapter({policy:{...providers[0],fetch:'permitted'},load},dates[0])).rejects.toThrow('display rights unknown');expect(load).not.toHaveBeenCalled();});
 it('rejects executable, credential-bearing and lookalike external URLs',()=>{for(const url of ['javascript:alert(1)','http://www.sec.gov/','https://www.sec.gov.evil.com','https://user:pass@www.sec.gov/','https://evil.com'])expect(safeLink(url)).toBeNull();expect(safeLink('https://www.sec.gov/')).toBeTruthy();});
 it('verified aliases preserve exchange namespaces and unknowns stay unmapped',()=>{expect(tradingView(assets[0])).toContain('NASDAQ%3AAAPL');expect(tradingView(assets[1])).toContain('AMEX%3ASPY');expect(tradingView({})).toBeNull();});
 it('retrieval cannot repair observation freshness',()=>{expect(freshness(null,'2024-01-01',1)).toBe('unavailable');expect(freshness('2020-01-01','2024-01-01',1800000)).toBe('stale');expect(freshness('2025-01-01','2024-01-01',1800000)).toBe('conflict');});
 const rows:BoardRow[]=[{id:'a',section:'stocks',close:12,previous:10,volume:100,dollarVolume:1200,eligible:true,fresh:true},{id:'b',section:'stocks',close:6,previous:10,volume:150,dollarVolume:900,eligible:true,fresh:true}];
 it('gainers/losers/share/dollar rankings are distinct with vacant slots',()=>{expect(board(rows,'stocks','gain').slots[0].id).toBe('a');expect(board(rows,'stocks','loss').slots[0].id).toBe('b');expect(board(rows,'stocks','share_volume').slots[0].id).toBe('b');expect(board(rows,'stocks','dollar_volume').slots[0].id).toBe('a');expect(board(rows,'stocks','gain').slots.filter(Boolean)).toHaveLength(1);expect(board(rows,'stocks','gain').slots).toHaveLength(10);expect(board(rows,'stocks','dollar_volume',false).status).toBe('data_unavailable');});
 it('rejects cross-section rows and stale filler',()=>{expect(()=>board(rows,'etfs','gain')).toThrow('Cross-section');expect(board(rows.map(r=>({...r,fresh:false})),'stocks','gain').slots.filter(Boolean)).toHaveLength(0);});
 const qualifiers=(section:'stocks'|'etfs',n:number):Candidate[]=>Array.from({length:n},(_,i)=>({id:String(i),section,score:80-i,coverage:.9,eligible:true,issuer:String(i),group:String(i),tags:i===0?['Dividend']:i===1?['Growth']:[],liquidity:1000}));
 it('independent success, shortage and outage outcomes never backfill',()=>{expect(candidates(qualifiers('stocks',5),'stocks').status).toBe('success');expect(candidates(qualifiers('etfs',2),'etfs').status).toBe('degraded');expect(candidates([],'stocks').slots.filter(Boolean)).toHaveLength(0);expect(candidates(qualifiers('etfs',5),'etfs',false).status).toBe('data_unavailable');expect(()=>candidates(qualifiers('stocks',5),'etfs')).toThrow();});
 it('issuer and ETF exposure duplicates cannot fill slots',()=>{expect(candidates(qualifiers('stocks',5).map(x=>({...x,issuer:'same'})),'stocks').slots.filter(Boolean)).toHaveLength(1);expect(candidates(qualifiers('etfs',5).map(x=>({...x,group:'same'})),'etfs').slots.filter(Boolean)).toHaveLength(1);});
 it('weights sum to 100; missing inputs reduce coverage and stocks alone have earnings penalty',()=>{for(const a of assets){const s=score(indicators(a.bars,dates[399]),a.section);expect(s.components.reduce((n,c)=>n+c.weight,0)).toBe(100);expect(s.coverage).toBeLessThan(.8);expect(s.eligible).toBe(false);expect(s.eventPenalty).toBe(a.section==='stocks'?5:0);expect(s.final).toBeCloseTo(Math.max(0,s.raw*s.coverage-s.eventPenalty),10);}});
});
describe('news validation and context isolation',()=>{const base:NewsItem={id:'a',title:'Original fixture title',publisher:'Fixture publisher',url:'https://www.sec.gov/example',publishedAt:'2024-01-01T12:00:00Z',entities:['us-aapl','us-spy'],permitted:true};const cutoff='2024-01-02T12:00:00Z';
 it('canonical dedup retains multi-asset links without guessing symbols',()=>{const rows=[base,{...base,id:'b',url:base.url+'?utm_source=test'}];expect(selectNews(rows,cutoff)).toHaveLength(1);expect(selectNews(rows,cutoff,'us-spy')).toHaveLength(1);expect(selectNews(rows,cutoff,'unknown')).toHaveLength(0);});
 it('rejects stale/future/unknown time, missing publisher, rights, retraction and unsafe URLs',()=>{const bad=[{publishedAt:'2020-01-01'},{publishedAt:'2025-01-01'},{publishedAt:'invalid'},{publisher:''},{permitted:false},{retracted:true},{url:'javascript:alert(1)'},{entities:[]}];for(const override of bad)expect(selectNews([{...base,...override}],cutoff)).toHaveLength(0);});
 it('similar distinct events are retained and changing news cannot alter scores',()=>{expect(selectNews([base,{...base,id:'b',url:'https://www.sec.gov/other'}],cutoff)).toHaveLength(2);const i=indicators(assets[0].bars,dates[399]),before=score(i,'stocks');selectNews([{...base,title:'Completely changed context'}],cutoff);expect(score(i,'stocks')).toEqual(before);});
});

it('news timestamp ordering respects explicit timezone offsets',()=>{const items:NewsItem[]=[{id:'later',title:'Later UTC',publisher:'Test',url:'https://www.sec.gov/later',publishedAt:'2024-01-02T05:00:00-06:00',entities:['broad-market'],permitted:true},{id:'earlier',title:'Earlier UTC',publisher:'Test',url:'https://www.sec.gov/earlier',publishedAt:'2024-01-02T10:00:00Z',entities:['broad-market'],permitted:true}];expect(selectNews(items,'2024-01-02T12:00:00Z')[0].id).toBe('later');});
