import {describe,it,expect} from 'vitest';
import {parseReplay} from '../src/replay';
const source={name:'Original test source',url:'https://www.eia.gov/opendata/',observedAt:'2024-01-01T12:00:00Z',retrievedAt:'2024-01-02T12:00:00Z',delaySeconds:null,rights:{display:'permitted',retention:'permitted',evidence:'Synthetic unit-test metadata, not real market evidence'}};
const base={version:1,mode:'replay',asOf:'2024-01-02T12:00:00Z',crypto:[{id:'bitcoin',chain:'Bitcoin',quoteCurrency:'USD',coverage:'aggregate',venue:null,price:'123.123456789',change24h:null,volume24hUsd:null,marketCapUsd:null,source}]};
describe('local permitted replay boundary',()=>{
 it('preserves decimal precision, unknown values and original observation timestamps',()=>{const x=parseReplay(JSON.stringify(base));expect(x.crypto[0].price).toBe('123.123456789');expect(x.crypto[0].marketCapUsd).toBeNull();expect(x.crypto[0].source.observedAt).toBe(source.observedAt);});
 it('rejects unknown rights, ticker/chain collision, future timestamps and duplicate identity',()=>{for(const c of [{...base.crypto[0],chain:'Ethereum'},{...base.crypto[0],source:{...source,rights:{...source.rights,display:'unknown'}}},{...base.crypto[0],source:{...source,observedAt:'2099-01-01T00:00:00Z'}}])expect(()=>parseReplay(JSON.stringify({...base,crypto:[c]}))).toThrow();expect(()=>parseReplay(JSON.stringify({...base,crypto:[base.crypto[0],base.crypto[0]]}))).toThrow('Duplicate');});
 it('venue fallback cannot inherit aggregate market cap',()=>{expect(()=>parseReplay(JSON.stringify({...base,crypto:[{...base.crypto[0],coverage:'venue',venue:'Example',marketCapUsd:'1000'}]}))).toThrow('aggregate market cap');});
 it('commodity physical unit and observation periods must be coherent',()=>{const c={id:'wti',type:'spot',value:'1',currency:'USD',unit:'USD/troy ounce',periodStart:'2024-01-01T00:00:00Z',periodEnd:'2024-01-01T00:00:00Z',frequency:'daily',source};expect(()=>parseReplay(JSON.stringify({...base,commodities:[c]}))).toThrow('unit mismatch');expect(parseReplay(JSON.stringify({...base,commodities:[{...c,unit:'USD/barrel'}]})).commodities[0].unit).toBe('USD/barrel');});
 it('refuses unknown keys/article bodies, future bars and excessive payload',()=>{expect(()=>parseReplay(JSON.stringify({...base,body:'Article text'}))).toThrow();expect(()=>parseReplay(' '.repeat(2000001))).toThrow('2 MB');expect(()=>parseReplay(JSON.stringify({...base,securities:[{id:'us-aapl',source,adjustment:'unadjusted',bars:[{date:'2024-01-03',open:1,high:1,low:1,close:1,volume:1}]}]}))).toThrow('Future bar');});
});
