// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {App} from '../src/main';
import {createElement} from 'react';
let root:Root;
const text=()=>document.body.textContent??'';
const button=(name:string)=>{const el=[...document.querySelectorAll('button')].find(b=>b.textContent===name);if(!el)throw Error('Missing button '+name);return el;};
async function click(el:Element){await act(async()=>{(el as HTMLElement).click();});}
async function navigate(path:string){await act(async()=>{history.pushState(null,'',path);window.dispatchEvent(new PopStateEvent('popstate'));});}
async function input(el:HTMLInputElement|HTMLTextAreaElement,value:string){await act(async()=>{const setter=Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!;setter.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});}
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();history.replaceState(null,'','/');vi.spyOn(window,'scrollTo').mockImplementation(()=>{});document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));});
afterEach(async()=>{await act(async()=>root.unmount());vi.restoreAllMocks();});
describe('runnable React research journey in DOM',()=>{
 it('renders brand, all section navigation, separate candidates and news vacancies',()=>{expect(text()).toContain('hi buy.com');for(const name of ['Top 5 Stock Research Candidates','Top 5 ETF Research Candidates','Top 5 Market News','SYNTHETIC TEST LAB'])expect(text()).toContain(name);expect(document.querySelectorAll('nav a')).toHaveLength(13);expect(document.querySelectorAll('h1')).toHaveLength(1);});
 it('saves literal text notes and watchlist, reloads and simulates next-step paper fill',async()=>{await navigate('/stocks/us-aapl');await click(button('Add to watchlist'));await click(button('Notes & scenarios'));const note=document.querySelector('textarea')!;await input(note,'Base case <script>not executable</script>');await click(button('Save note'));expect(JSON.parse(localStorage.getItem('hi-buy-com:v1')!).notes['us-aapl']).toBe('Base case <script>not executable</script>');expect(document.querySelector('script')).toBeNull();await click(button('Paper plan'));await act(async()=>{document.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});await navigate('/stocks/paper');expect(text()).toContain('pending');await click(button('Advance one session →'));expect(text()).toContain('Next-session open + 10 bps');expect(document.querySelector('.paper-row .badge')!.textContent).toBe('open');await navigate('/etfs/paper');expect(text()).toContain('No paper intents');expect(document.querySelectorAll('.metric strong')[0].textContent).toBe('100000.00');await act(async()=>root.unmount());root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));await navigate('/stocks/us-aapl');await click(button('Notes & scenarios'));expect(document.querySelector('textarea')!.value).toBe('Base case <script>not executable</script>');});
 it('shows chart-equivalent OHLCV table and explicit source details',async()=>{await navigate('/stocks/us-aapl');await click(button('Show chart data table'));expect(document.querySelectorAll('table')).toHaveLength(2);expect(document.querySelector('table tbody')!.children).toHaveLength(70);expect(text()).toContain('deterministic-sine-v1');expect(document.querySelector('svg')!.getAttribute('aria-label')).toContain('synthetic');});
 it('provides eight separate boards and no invented current crypto or commodity prices',async()=>{for(const s of ['stocks','etfs']){await navigate(`/${s}/boards`);expect(document.querySelectorAll('.slots')).toHaveLength(4);expect(document.querySelectorAll('.slots li')).toHaveLength(40);}await navigate('/crypto');for(const symbol of ['BTC','ETH','SOL'])expect(text()).toContain(symbol);expect(document.querySelectorAll('.price')).toHaveLength(3);for(const el of document.querySelectorAll('.price'))expect(el.textContent).toBe('Unavailable');await navigate('/commodities');expect(document.querySelectorAll('.price')).toHaveLength(8);expect(text()).toContain('Contango/backwardation unavailable');});
 it('external links are allowlisted, isolated and no content resources are remote',async()=>{await navigate('/etfs/us-spy');const links=[...document.querySelectorAll('a[target="_blank"]')];expect(links.some(l=>l.getAttribute('href')?.includes('AMEX%3ASPY'))).toBe(true);for(const link of links)expect(link.getAttribute('rel')).toBe('noopener noreferrer');expect(document.querySelectorAll('iframe,img,script[src^="https:"]')).toHaveLength(0);});
 it('invalid instruments stay explicit and paper reset requires confirmation',async()=>{await navigate('/stocks/unmapped');expect(text()).toContain('Unknown instrument');await navigate('/settings');const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await click(button('Delete private data / reset'));expect(confirm).toHaveBeenCalledOnce();expect(text()).not.toContain('Private data deleted');});
});

it('does not overwrite corrupt private storage during startup',async()=>{await act(async()=>root.unmount());localStorage.setItem('hi-buy-com:v1','{corrupted-but-preserved');root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));expect(text()).toContain('Saved data invalid');expect(localStorage.getItem('hi-buy-com:v1')).toBe('{corrupted-but-preserved');});
