// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {App} from '../src/main';
import {createElement} from 'react';
let root:Root;
const text=()=>document.body.textContent??'';
const button=(name:string)=>{const el=[...document.querySelectorAll('button')].find(b=>b.textContent===name);if(!el)throw Error('Missing button '+name);return el;};
async function click(el:Element){await act(async()=>{(el as HTMLElement).click();});}
async function navigate(path:string){await act(async()=>{history.pushState(null,'',path);window.dispatchEvent(new PopStateEvent('popstate'));});}
async function input(el:HTMLInputElement|HTMLTextAreaElement,value:string){await act(async()=>{const setter=Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!;setter.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});}
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();history.replaceState(null,'','/');vi.spyOn(window,'scrollTo').mockImplementation(()=>{});document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));});
afterEach(async()=>{await act(async()=>root.unmount());vi.restoreAllMocks();});
describe('runnable React research journey in DOM',()=>{
 it('renders brand, all section navigation, separate candidates and news vacancies',()=>{expect(text()).toContain('hi buy.com');for(const name of ['Top 5 Stock Research Candidates','Top 5 ETF Research Candidates','Top 5 Market News','SYNTHETIC TEST LAB'])expect(text()).toContain(name);expect(document.querySelectorAll('nav a')).toHaveLength(13);expect(document.querySelectorAll('h1')).toHaveLength(1);});
 it('saves literal text notes and watchlist, reloads and simulates next-step paper fill',async()=>{await navigate('/stocks/us-aapl');await click(button('Add to watchlist'));await click(button('Notes & scenarios'));const note=document.querySelector('textarea')!;await input(note,'Base case <script>not executable</script>');await click(button('Save note'));expect(JSON.parse(localStorage.getItem('hi-buy-com:v1')!).notes['us-aapl']).toBe('Base case <script>not executable</script>');expect(document.querySelector('script')).toBeNull();await click(button('Paper plan'));await act(async()=>{document.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});await navigate('/stocks/paper');expect(text()).toContain('pending');await click(button('Advance one session →'));expect(text()).toContain('Next-session open + 10 bps');expect(document.querySelector('.paper-row .badge')!.textContent).toBe('open');await navigate('/etfs/paper');expect(text()).toContain('No paper intents');expect(document.querySelectorAll('.metric strong')[0].textContent).toBe('100000.00');await act(async()=>root.unmount());root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));await navigate('/stocks/us-aapl');await click(button('Notes & scenarios'));expect(document.querySelector('textarea')!.value).toBe('Base case <script>not executable</script>');});
 it('shows chart-equivalent OHLCV table and explicit source details',async()=>{await navigate('/stocks/us-aapl');await click(button('Show chart data table'));expect(document.querySelectorAll('table')).toHaveLength(2);expect(document.querySelector('table tbody')!.children).toHaveLength(70);expect(text()).toContain('deterministic-sine-v1');expect(document.querySelector('svg')!.getAttribute('aria-label')).toContain('synthetic');});
 it('provides eight separate boards and no invented current crypto or commodity prices',async()=>{for(const s of ['stocks','etfs']){await navigate(`/${s}/boards`);expect(document.querySelectorAll('.slots')).toHaveLength(4);expect(document.querySelectorAll('.slots li')).toHaveLength(40);}await navigate('/crypto');for(const symbol of ['BTC','ETH','SOL'])expect(text()).toContain(symbol);expect(document.querySelectorAll('.price')).toHaveLength(3);for(const el of document.querySelectorAll('.price'))expect(el.textContent).toBe('Unavailable');await navigate('/commodities');expect(document.querySelectorAll('.price')).toHaveLength(8);expect(text()).toContain('Contango/backwardation unavailable');});
 it('external links are allowlisted, isolated and no content resources are remote',async()=>{await navigate('/etfs/us-spy');const links=[...document.querySelectorAll('a[target="_blank"]')];expect(links.some(l=>l.getAttribute('href')?.includes('AMEX%3ASPY'))).toBe(true);for(const link of links)expect(link.getAttribute('rel')).toBe('noopener noreferrer');expect(document.querySelectorAll('iframe,img,script[src^="https:"]')).toHaveLength(0);});
 it('invalid instruments stay explicit and paper reset requires confirmation',async()=>{await navigate('/stocks/unmapped');expect(text()).toContain('Unknown instrument');await navigate('/settings');const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await click(button('Delete private data / reset'));expect(confirm).toHaveBeenCalledOnce();expect(text()).not.toContain('Private data deleted');});
});

it('does not overwrite corrupt private storage during startup',async()=>{await act(async()=>root.unmount());localStorage.setItem('hi-buy-com:v1','{corrupted-but-preserved');root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));expect(text()).toContain('Saved data invalid');expect(localStorage.getItem('hi-buy-com:v1')).toBe('{corrupted-but-preserved');});

it('toggles dark mode with semantic pressed state and persists across remount',async()=>{const toggle=document.querySelector('button[aria-label="Dark mode"]')!;await click(toggle);expect(toggle.getAttribute('aria-pressed')).toBe('true');expect(localStorage.getItem('hi-buy-theme')).toBe('dark');expect(document.documentElement.dataset.theme).toBe('dark');await act(async()=>root.unmount());root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));expect(document.querySelector('button[aria-label="Dark mode"]')!.getAttribute('aria-pressed')).toBe('true');});
it('refreshes the same-origin snapshot and exposes fetch failures',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({version:1,entries:{}}),{status:200,headers:{'Content-Type':'application/json'}}));await click(button('Refresh snapshot'));expect(fetcher.mock.calls[0][0]).toMatch(/^\/live\/latest.json\?t=/);expect(text()).not.toContain('Last snapshot retrieved by this browser: Not yet');fetcher.mockRejectedValueOnce(Error('offline'));await click(button('Refresh snapshot'));expect(text()).toContain('Snapshot fetch failed: offline');});
it('respects system dark preference on first visit',async()=>{await act(async()=>root.unmount());vi.stubGlobal('matchMedia',()=>({matches:true}));root=createRoot(document.getElementById('root')!);await act(async()=>root.render(createElement(App)));expect(document.querySelector('button[aria-label="Dark mode"]')!.getAttribute('aria-pressed')).toBe('true');vi.unstubAllGlobals();});
it('renders real snapshot values and stale provenance separately from synthetic calculations',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({version:1,entries:{bitcoin:{source:'Data provided by CoinGecko',url:'https://www.coingecko.com/en/api',unit:'USD',delay:'Unknown',retrievedAt:'2020-01-01T00:00:00Z',observedAt:'2020-01-01T00:00:00Z',status:'available',error:null,price:123,change:2,volume:500,marketCap:900,bars:[]}}})));await click(button('Refresh snapshot'));await navigate('/crypto');expect(document.querySelector('.price')!.textContent).toBe('123');expect(text()).toContain('Stale retrieval');expect(text()).toContain('Source retrieved: 2020-01-01');});
it('shows valid public OHLCV only in its own labeled workspace',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({version:1,entries:{AAPL:{source:'Permitted test response',url:'https://example.com/source',unit:'USD',delay:'Delayed',retrievedAt:'2026-09-19T12:00:00Z',observedAt:'2026-09-18T20:00:00Z',status:'available',error:null,price:102,change:null,volume:null,marketCap:null,bars:[{date:'2026-09-18',open:100,high:103,low:99,close:102,volume:1000}]}}})));await click(button('Refresh snapshot'));await navigate('/stocks/us-aapl');expect(document.querySelector('svg[aria-label="AAPL public-source daily close chart"]')).not.toBeNull();expect(document.querySelector('svg[aria-label*="synthetic"]')).not.toBeNull();expect(text()).toContain('Public observations never enter synthetic scores');});
it('theme remains usable when browser storage is blocked',async()=>{vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('blocked');});await click(document.querySelector('button[aria-label="Dark mode"]')!);expect(document.documentElement.dataset.theme).toBe('dark');});

it('renders keyless numeric crypto fields when provider timestamp is absent',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({version:1,entries:{bitcoin:{source:'Data provided by CoinGecko',url:'https://www.coingecko.com/en/api',unit:'USD',delay:'Aggregate / cached; delay unknown',retrievedAt:new Date().toISOString(),observedAt:null,status:'available',error:null,price:63123.45,change:-1.25,volume:23456789012,marketCap:1234567890123,bars:[]}}})));await click(button('Refresh snapshot'));await navigate('/crypto');expect(document.querySelector('.price')!.textContent).toBe('63,123.45');for(const value of ['-1.25%','23,456,789,012','1,234,567,890,123','Provider timestamp unavailable','Source retrieved:'])expect(text()).toContain(value);});
