import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {parseSnapshot,entrySchema} from '../src/snapshot.ts';
const nulls={observedAt:null,price:null,change:null,volume:null,marketCap:null,bars:[]};
export function yahoo(raw){const r=raw.chart?.result?.[0];if(!r||raw.chart.error)throw Error('Invalid Yahoo response');const q=r.indicators?.quote?.[0];const bars=(r.timestamp??[]).flatMap((t,i)=>[q?.open?.[i],q?.high?.[i],q?.low?.[i],q?.close?.[i],q?.volume?.[i]].every(Number.isFinite)?[{date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i],high:q.high[i],low:q.low[i],close:q.close[i],volume:q.volume[i]}]:[]);if(!bars.length)throw Error('No valid OHLCV');return {price:r.meta.regularMarketPrice,observedAt:new Date(r.meta.regularMarketTime*1000).toISOString(),bars};}
export function fred(csv){const rows=csv.trim().split(/\r?\n/).slice(1).map(l=>l.split(','));const valid=rows.filter(([d,v])=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d&&v!==''&&v!=='.'&&Number.isFinite(Number(v)));if(!valid.length)throw Error('No dated numeric series');const [date,value]=valid.at(-1);return {price:Number(value),observedAt:date+'T00:00:00.000Z'};}
export function coin(raw,id){const r=raw[id];if(!r||![r.usd,r.usd_24h_change,r.usd_24h_vol,r.usd_market_cap].every(Number.isFinite))throw Error('Missing crypto fields');return {price:r.usd,change:r.usd_24h_change,volume:r.usd_24h_vol,marketCap:r.usd_market_cap,observedAt:Number.isFinite(r.last_updated_at)?new Date(r.last_updated_at*1000).toISOString():null};}
export function stabilize(next,previous){for(const [id,e] of Object.entries(next.entries)){const old=previous?.entries[id];if(old&&JSON.stringify({...old,retrievedAt:''})===JSON.stringify({...e,retrievedAt:''}))next.entries[id]=old;}return next;}
export async function generate(fetcher=fetch){const entries={};const retrievedAt=new Date().toISOString();const get=async(url,json=true)=>{const r=await fetcher(url,{signal:AbortSignal.timeout(15000),headers:{'User-Agent':'hi-buy-public-snapshot/1.0','Accept':json?'application/json':'text/csv'}});if(!r.ok)throw Error('HTTP '+r.status);return json?r.json():r.text();};
async function collect(id,source,url,unit,delay,fn){let e={source,url,unit,delay,retrievedAt,status:'unavailable',error:null,...nulls};try{e={...e,...await fn(),status:'available'};entrySchema.parse(e);}catch(err){e={...e,...nulls,status:'unavailable',error:err instanceof Error?err.message:'Source failed'};}entries[id]=entrySchema.parse(e);}
for(const symbol of ['AAPL','SPY'])await collect(symbol,'Yahoo chart (unofficial)','https://finance.yahoo.com/quote/'+symbol+'/','USD','Unofficial / potentially delayed; rights-unverified; not a licensed consolidated feed',async()=>yahoo(await get(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=6mo&interval=1d`)));
let coins;let coinError;try{coins=await get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true&include_last_updated_at=true');}catch(e){coinError=e;}
for(const id of ['bitcoin','ethereum','solana'])await collect(id,'Data provided by CoinGecko','https://www.coingecko.com/en/api','USD','Aggregate / cached; delay unknown',async()=>{if(coinError)throw coinError;return coin(coins,id);});
for(const [id,series,unit] of [['wti','DCOILWTICO','USD / barrel'],['brent','DCOILBRENTEU','USD / barrel'],['natural-gas','DHHNGSP','USD / million Btu']])await collect(id,'EIA via FRED',`https://fred.stlouisfed.org/series/${series}`,unit,'Dated daily benchmark; publication lag, not a quote',async()=>fred(await get(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${series}`,false)));
for(const id of ['gold','silver','copper','corn','wheat'])await collect(id,'FRED catalog','https://fred.stlouisfed.org/','Source-specific units','No approved series',async()=>{throw Error('No verified keyless series with defensible redistribution rights');});
return parseSnapshot({version:1,entries});}
async function main(){const file=process.argv.find(a=>a.startsWith('--output='))?.slice(9)??'public/live/latest.json';let previous;try{previous=parseSnapshot(JSON.parse(await readFile(file,'utf8')));}catch{}const next=stabilize(await generate(),previous);const content=JSON.stringify(next,null,2)+'\n';if(JSON.stringify(next)!==JSON.stringify(previous)){await mkdir(dirname(file),{recursive:true});await writeFile(file,content);console.log('Snapshot changed:',file);}else console.log('Snapshot unchanged');for(const [id,e] of Object.entries(next.entries))console.log(id,e.status,e.error??e.observedAt);}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)await main();
