import type {Bar,Section} from './domain';
export const fixtureManifest={id:'synthetic-lab-v1',mode:'synthetic_test',generator:'deterministic-sine-v1',createdAt:'2026-09-19',rights:'Original mathematical test vectors; redistribution permitted by project author. No vendor data.',warning:'SYNTHETIC TEST DATA — not historical or current real-world prices',adjustment:'No real corporate actions; test-only unadjusted OHLCV',feed:'local mathematical vectors',delay:'Not a market feed',retrievedAt:'2026-09-19T00:00:00Z'} as const;
export type Asset={id:string;symbol:string;name:string;section:Section;exchange:string;tags:string[];official:string;tv?:{qualified:string;overview:string};bars:Bar[]};
export function vectors(seed:number):Bar[]{const result:Bar[]=[];const d=new Date('2023-01-02T00:00:00Z');for(let n=0;n<440;){if(d.getUTCDay()!==0&&d.getUTCDay()!==6){const close=70+seed*30+n*.085+8*Math.sin(n/12+seed)+2*Math.sin(n/3),open=close+Math.sin(n)*1.2;result.push({date:d.toISOString().slice(0,10),open,close,high:Math.max(open,close)+1.4,low:Math.min(open,close)-1.4,volume:Math.round(1300000+400000*Math.sin(n/8+seed))});n++;}d.setUTCDate(d.getUTCDate()+1);}return result;}
export const assets:Asset[]=[{id:'us-aapl',symbol:'AAPL',name:'Apple · identity example',section:'stocks',exchange:'NASDAQ',tags:[],official:'https://investor.apple.com/',tv:{qualified:'NASDAQ:AAPL',overview:'https://www.tradingview.com/symbols/NASDAQ-AAPL/'},bars:vectors(1)},{id:'us-spy',symbol:'SPY',name:'SPDR S&P 500 ETF Trust · identity example',section:'etfs',exchange:'NYSE Arca',tags:['Core/Broad Market'],official:'https://www.ssga.com/us/en/institutional/etfs/state-street-spdr-sp-500-etf-trust-spy',tv:{qualified:'AMEX:SPY',overview:'https://www.tradingview.com/symbols/AMEX-SPY/'},bars:vectors(2)}];
export const dates=assets[0].bars.map(b=>b.date);
export const allowedHosts=new Set(['www.tradingview.com','investor.apple.com','www.ssga.com','www.sec.gov','www.eia.gov','fred.stlouisfed.org','www.coingecko.com','bitcoin.org','ethereum.org','solana.com']);
export function safeLink(value:string){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&allowedHosts.has(u.hostname)?u.href:null;}catch{return null;}}
export function tradingView(a:Pick<Asset,'tv'>){return a.tv?`https://www.tradingview.com/chart/?symbol=${encodeURIComponent(a.tv.qualified)}`:null;}
export const commodities=[{id:'gold',name:'Gold',group:'Metals',unit:'USD / troy ounce'},{id:'silver',name:'Silver',group:'Metals',unit:'USD / troy ounce'},{id:'wti',name:'WTI crude',group:'Energy',unit:'USD / barrel'},{id:'brent',name:'Brent crude',group:'Energy',unit:'USD / barrel'},{id:'natural-gas',name:'Natural gas',group:'Energy',unit:'USD / million Btu'},{id:'copper',name:'Copper',group:'Metals',unit:'Series not approved'},{id:'corn',name:'Corn',group:'Agriculture',unit:'Series not approved'},{id:'wheat',name:'Wheat',group:'Agriculture',unit:'Series not approved'}];
export const crypto=[{id:'bitcoin',symbol:'BTC',chain:'Bitcoin',source:'https://www.coingecko.com/en/coins/bitcoin',explorer:'https://bitcoin.org/'},{id:'ethereum',symbol:'ETH',chain:'Ethereum',source:'https://www.coingecko.com/en/coins/ethereum',explorer:'https://ethereum.org/'},{id:'solana',symbol:'SOL',chain:'Solana',source:'https://www.coingecko.com/en/coins/solana',explorer:'https://solana.com/'}];
export type Rights='permitted'|'unknown'|'denied';
export type ProviderPolicy={id:string;section:string;fetch:Rights;display:Rights;retention:Rights;export:Rights;derived:Rights;source:string;observation:string|null;delaySeconds:number|null};
export const providers:ProviderPolicy[]=[{id:'securities',section:'stocks / etfs',source:'Alpaca historical consolidated (proposed)',fetch:'unknown',display:'unknown',retention:'unknown',export:'unknown',derived:'unknown',observation:null,delaySeconds:null},{id:'crypto',section:'crypto',source:'CoinGecko Demo (proposed)',fetch:'unknown',display:'unknown',retention:'unknown',export:'unknown',derived:'unknown',observation:null,delaySeconds:null},{id:'commodities',section:'commodities',source:'EIA / series-level review required',fetch:'unknown',display:'unknown',retention:'unknown',export:'unknown',derived:'unknown',observation:null,delaySeconds:null},{id:'news',section:'news',source:'Reviewed issuer / SEC metadata (proposed)',fetch:'unknown',display:'unknown',retention:'unknown',export:'unknown',derived:'unknown',observation:null,delaySeconds:null}];
export function assertCapability(p:ProviderPolicy,capability:keyof Pick<ProviderPolicy,'fetch'|'display'|'retention'|'export'|'derived'>){if(p[capability]!=='permitted')throw Error(`${p.id}: ${capability} rights ${p[capability]}; capability disabled`);}
export function freshness(observation:string|null,now:string,maxAgeMs:number){if(!observation)return 'unavailable';const age=Date.parse(now)-Date.parse(observation);return !Number.isFinite(age)||age<0?'conflict':age>maxAgeMs?'stale':'fresh';}
export interface DataAdapter<T>{policy:ProviderPolicy;load(asOf:string):Promise<T>;}
/** Capability checks precede even a user-supplied optional read-only adapter. No live transport is bundled. */
export async function readAdapter<T>(adapter:DataAdapter<T>,asOf:string){assertCapability(adapter.policy,'fetch');assertCapability(adapter.policy,'display');return adapter.load(asOf);}
export type NewsItem={id:string;title:string;publisher:string;url:string;publishedAt:string;entities:string[];permitted:boolean;syndication?:string;retracted?:boolean};
export function selectNews(items:NewsItem[],asOf:string,assetId?:string){const seen=new Set<string>();return items.filter(x=>x.permitted&&!x.retracted&&x.title.trim()&&x.publisher.trim()&&safeLink(x.url)&&x.entities.length&&(!assetId||x.entities.includes(assetId))&&Number.isFinite(Date.parse(x.publishedAt))&&Date.parse(x.publishedAt)<=Date.parse(asOf)&&Date.parse(asOf)-Date.parse(x.publishedAt)<=(assetId?30*86400000:48*3600000)).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)||a.id.localeCompare(b.id)).filter(x=>{const u=new URL(x.url);for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_')||k==='fbclid')u.searchParams.delete(k);u.hash='';const key=x.syndication??u.href;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,assetId?100:5);}
export type BoardRow={id:string;section:Section;close:number;previous:number;volume:number;dollarVolume:number;eligible:boolean;fresh:boolean};
export function board(rows:BoardRow[],section:Section,rank:'gain'|'loss'|'share_volume'|'dollar_volume',permitted=true){if(rows.some(x=>x.section!==section))throw Error('Cross-section rows rejected');if(!permitted)return {status:'data_unavailable',slots:Array(10).fill(null)};const change=(x:BoardRow)=>(x.close/x.previous-1)*100;const valid=rows.filter(x=>x.eligible&&x.fresh&&x.close>0&&x.previous>0&&(rank==='gain'?change(x)>0:rank==='loss'?change(x)<0:true));const metric=(x:BoardRow)=>rank==='gain'?change(x):rank==='loss'?-change(x):rank==='share_volume'?x.volume:x.dollarVolume;valid.sort((a,b)=>metric(b)-metric(a)||b.dollarVolume-a.dollarVolume||a.id.localeCompare(b.id));return {status:valid.length>=10?'success':'degraded',slots:Array.from({length:10},(_,i)=>valid[i]??null)};}
export type Candidate={id:string;section:Section;score:number;coverage:number;eligible:boolean;issuer:string;group:string;tags:string[];liquidity:number};
export function candidates(rows:Candidate[],section:Section,available=true){if(rows.some(x=>x.section!==section))throw Error('Cross-section candidate rejected');const picked:Candidate[]=[],warnings:string[]=[];if(available){const sorted=rows.filter(x=>x.eligible&&x.score>=60&&x.coverage>=.8).sort((a,b)=>b.score-a.score||b.liquidity-a.liquidity||a.id.localeCompare(b.id));const unique=(x:Candidate)=>!picked.some(y=>section==='stocks'?y.issuer===x.issuer:y.group===x.group);if(section==='etfs')for(const tag of ['Dividend','Growth']){const x=sorted.find(x=>x.tags.includes(tag)&&unique(x));if(x)picked.push(x);else warnings.push(`${tag} quota unavailable`);}for(const x of sorted){if(picked.length===5)break;if(unique(x)&&picked.filter(y=>y.group===x.group).length<2)picked.push(x);}for(const x of sorted){if(picked.length===5)break;if(unique(x)){picked.push(x);warnings.push('Sector preference relaxed');}}}return {status:!available?'data_unavailable':picked.length===5?'success':'degraded',slots:Array.from({length:5},(_,i)=>picked[i]??null),warnings};}
