import React,{createContext,useContext,useEffect,useState} from 'react';
import {parseSnapshot,freshness,type Snapshot,type Entry} from './snapshot';
const Context=createContext<Snapshot|null>(null);
export function ThemeToggle(){const [dark,setDark]=useState(()=>{try{const saved=localStorage.getItem('hi-buy-theme');if(saved==='dark'||saved==='light')return saved==='dark';}catch{}return window.matchMedia?.('(prefers-color-scheme: dark)').matches??false;});useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);return <button aria-label="Dark mode" aria-pressed={dark} onClick={()=>{setDark(!dark);try{localStorage.setItem('hi-buy-theme',dark?'light':'dark');}catch{}}}>Dark mode</button>;}
export function LiveProvider({children}:{children:React.ReactNode}){const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[retrieved,setRetrieved]=useState('Not yet'),[busy,setBusy]=useState(false);const [,tick]=useState(0);async function refresh(){setBusy(true);try{const response=await fetch(`${import.meta.env.BASE_URL}live/latest.json?t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error(`HTTP ${response.status}`);setSnapshot(parseSnapshot(await response.json()));setRetrieved(new Date().toISOString());setError('');}catch(e){setError(`Snapshot fetch failed: ${e instanceof Error?e.message:'unknown error'}. Retained values may be stale.`);}finally{setBusy(false);}}useEffect(()=>{void refresh();const timer=setInterval(()=>tick(v=>v+1),60000);return()=>clearInterval(timer);},[]);return <Context.Provider value={snapshot?{...snapshot}:null}><section className="panel live-status" aria-label="Public snapshot status"><h2>Public-source snapshot</h2><button onClick={()=>void refresh()} disabled={busy}>{busy?'Retrieving snapshot…':'Refresh snapshot'}</button><p aria-live="polite">Last snapshot retrieved by this browser: {retrieved}. {error}</p><p className="fine">Scheduled every five minutes; GitHub scheduling and deployment may lag. Refresh reads the published file; it does not run the GitHub Action. Source retrieval times below advance only when data or status changes. Unchanged data can become stale.</p></section>{children}</Context.Provider>;}
const format=(v:number|null,unit='')=>v===null?'Unavailable':`${v.toLocaleString('en-US',{maximumFractionDigits:2})}${unit}`;
function Provenance({entry}:{entry:Entry}){return <><p>{freshness(entry)} · {entry.delay}</p><p className="fine">Observed: {entry.observedAt??'Provider timestamp unavailable (retrieval time only)'} · Source retrieved: {entry.retrievedAt}</p><a href={entry.url} target="_blank" rel="noopener noreferrer">{entry.source} ↗</a>{entry.error&&<p className="notice">{entry.error}</p>}</>;}
export function LiveValue({id,details=false}:{id:string;details?:boolean}){const entry=useContext(Context)?.entries[id];return <><div className="price">{entry?format(entry.price):'Unavailable'}</div>{entry&&<><p>{entry.unit}</p>{details&&<dl><dt>Rolling 24h change</dt><dd>{format(entry.change,'%')}</dd><dt>24h volume (USD)</dt><dd>{format(entry.volume)}</dd><dt>Market cap (USD)</dt><dd>{format(entry.marketCap)}</dd></dl>}<Provenance entry={entry}/></>}</>;}
export function LiveWorkspace({symbol}:{symbol:string}){const entry=useContext(Context)?.entries[symbol];const bars=entry?.status==='available'?entry.bars:[];return <section className="panel"><h2>{symbol} public market snapshot</h2><LiveValue id={symbol}/>{bars.length>0&&<><svg className="chart" viewBox="0 0 700 200" role="img" aria-label={`${symbol} public-source daily close chart`}><polyline fill="none" stroke="currentColor" strokeWidth="2" points={bars.map((b,i)=>`${i*690/Math.max(1,bars.length-1)},${190-(b.close-Math.min(...bars.map(b=>b.low)))/Math.max(1,Math.max(...bars.map(b=>b.high))-Math.min(...bars.map(b=>b.low)))*180}`).join(' ')}/></svg><details><summary>Public OHLCV data</summary><div className="table-scroll"><table><caption>Public-source daily bars; last bar may be incomplete</caption><thead><tr>{['Date','Open','High','Low','Close','Volume'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{bars.map(b=><tr key={b.date}>{[b.date,b.open,b.high,b.low,b.close,b.volume].map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></details></>}<p>Public observations never enter synthetic scores, alerts or paper fills. They are excluded from candidates, rankings and exports. Rankings remain unavailable: universe and eligibility gates are incomplete.</p></section>;}
