import Decimal from 'decimal.js';
import {z} from 'zod';
import {assets,dates} from './data';
import type {Bar,Section} from './domain';
export const intentSchema=z.object({id:z.string().min(1).max(100),assetId:z.enum(['us-aapl','us-spy']),section:z.enum(['stocks','etfs']),createdAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),quantity:z.number().int().min(1).max(10000),stop:z.number().positive(),target:z.number().positive()});
export type Intent=z.infer<typeof intentSchema>;
export type Position=Intent&{state:'pending'|'open'|'closed'|'cancelled';entry?:string;exit?:string;filledAt?:string;closedAt?:string;pnl?:string;reason:string};
export function simulate(raw:Intent[],section:Section,asOf:string,source:Record<string,Bar[]>=Object.fromEntries(assets.map(a=>[a.id,a.bars]))){
 let cash=new Decimal(100000);const positions:Position[]=[];const ids=new Set<string>();
 for(const item of [...raw].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))){const p=intentSchema.parse(item);if(p.section!==section||assets.find(a=>a.id===p.assetId)?.section!==section)throw Error('Cross-section paper intent rejected');if(p.target<=p.stop||!dates.includes(p.createdAt))throw Error('Invalid paper plan');if(ids.has(p.id))continue;ids.add(p.id);if(p.createdAt>asOf)continue;positions.push({...p,state:'pending',reason:'Waiting for next synthetic session; manual test plan'});}
 const timeline=[...new Set(Object.values(source).flatMap(b=>b.map(x=>x.date)))].filter(d=>d<=asOf).sort();
 for(const date of timeline)for(const p of positions){const b=source[p.assetId]?.find(b=>b.date===date);if(!b||date<=p.createdAt||p.state==='closed'||p.state==='cancelled')continue;
 if(p.state==='pending'){const prev=source[p.assetId].filter(x=>x.date<date).slice(-20);const adv=prev.reduce((s,x)=>s+x.volume,0)/prev.length;const entry=new Decimal(b.open).mul('1.001').toDecimalPlaces(2,Decimal.ROUND_UP);const cost=entry.mul(p.quantity);if(p.quantity>Math.floor(Math.min(.01*adv,.1*b.volume))||cost.gt(cash)||entry.lte(p.stop)||entry.gte(p.target)){p.state='cancelled';p.reason='Cash, participation, or gap outside plan bounds';continue;}cash=cash.minus(cost);p.entry=entry.toFixed(2);p.filledAt=date;p.state='open';p.reason='Next-session open + 10 bps adverse slippage; coarse daily fill';}
 if(p.state==='open'){const holding=source[p.assetId].filter(x=>x.date>=p.filledAt!&&x.date<date).length;let exit:Decimal|undefined;if(b.low<=p.stop){exit=new Decimal(Math.min(b.open,p.stop)).mul('.999');p.reason=b.high>=p.target?'Stop first: same-bar target/stop ambiguity':'Stop or adverse gap; 10 bps exit slippage';}else if(b.high>=p.target){if(p.filledAt===date){p.reason='Entry-bar target ordering indeterminate; target fill deferred';continue;}exit=new Decimal(p.target);p.reason='Conservative target-limit fill';}else if(holding>=20){exit=new Decimal(b.open).mul('.999');p.reason='20-session time exit';}if(exit){exit=exit.toDecimalPlaces(2,Decimal.ROUND_DOWN);p.exit=exit.toFixed(2);p.closedAt=date;p.state='closed';p.pnl=exit.minus(p.entry!).mul(p.quantity).toFixed(2);cash=cash.plus(exit.mul(p.quantity));}}
 }
 let equity=cash;for(const p of positions.filter(p=>p.state==='open')){const mark=source[p.assetId].filter(b=>b.date<=asOf).at(-1);if(mark)equity=equity.plus(new Decimal(mark.close).mul(p.quantity));}return {cash:cash.toFixed(2),equity:equity.toFixed(2),positions};
}
export const stateSchema=z.object({version:z.literal(1),cursor:z.number().int().min(399).max(439),notes:z.record(z.string(),z.string().max(10000)),watch:z.array(z.enum(['us-aapl','us-spy'])),intents:z.array(intentSchema),screens:z.record(z.string(),z.string().max(500)),alerts:z.array(z.object({id:z.string(),assetId:z.enum(['us-aapl','us-spy']),threshold:z.number().positive(),createdAt:z.string(),paused:z.boolean()}))});
export type LocalState=z.infer<typeof stateSchema>;
export const initialState:LocalState={version:1,cursor:399,notes:{},watch:[],intents:[],screens:{},alerts:[]};
export function restore(value:string){const s=stateSchema.parse(JSON.parse(value));for(const i of s.intents){if(assets.find(a=>a.id===i.assetId)?.section!==i.section||i.target<=i.stop||!dates.includes(i.createdAt))throw Error('Invalid account association');}return s;}
export function alertEvents(state:LocalState){return state.alerts.flatMap(rule=>{if(rule.paused)return [];const a=assets.find(a=>a.id===rule.assetId)!;return a.bars.slice(1,state.cursor+1).flatMap((b,i)=>b.date>rule.createdAt&&b.close>rule.threshold&&a.bars[i].close<=rule.threshold?[{id:`${rule.id}:${b.date}:cross-up`,date:b.date,symbol:a.symbol,message:`Synthetic close crossed above ${rule.threshold}. Replay event; not a protective order.`}]:[]);});}
