import {z} from 'zod';
import {safeLink,selectNews} from './data';
import {validateBars} from './domain';
const iso=z.string().datetime({offset:true});
const decimal=z.string().regex(/^(?:0|[1-9]\d*)(?:\.\d+)?$/).refine(v=>Number.isFinite(Number(v))&&Number(v)>0,'Expected positive finite decimal');
const source=z.object({name:z.string().min(1).max(200),url:z.string().url().refine(v=>safeLink(v)!==null,'Source host must be in the reviewed outbound registry'),observedAt:iso,retrievedAt:iso,delaySeconds:z.number().nonnegative().nullable(),rights:z.object({display:z.literal('permitted'),retention:z.literal('permitted'),evidence:z.string().min(10).max(2000)})}).strict();
const bar=z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),open:z.number().positive(),high:z.number().positive(),low:z.number().positive(),close:z.number().positive(),volume:z.number().int().nonnegative()}).strict();
export const replaySchema=z.object({version:z.literal(1),mode:z.literal('replay'),asOf:iso,securities:z.array(z.object({id:z.enum(['us-aapl','us-spy']),source,adjustment:z.enum(['split-adjusted, non-dividend-adjusted','unadjusted']),bars:z.array(bar).min(1).max(5000)}).strict()).max(2).default([]),crypto:z.array(z.object({id:z.enum(['bitcoin','ethereum','solana']),chain:z.enum(['Bitcoin','Ethereum','Solana']),quoteCurrency:z.literal('USD'),coverage:z.enum(['aggregate','venue']),venue:z.string().min(1).nullable(),price:decimal,change24h:z.number().finite().nullable(),volume24hUsd:z.string().regex(/^\d+(?:\.\d+)?$/).nullable(),marketCapUsd:z.string().regex(/^\d+(?:\.\d+)?$/).nullable(),source}).strict()).max(3).default([]),commodities:z.array(z.object({id:z.enum(['gold','silver','wti','brent','natural-gas','copper','corn','wheat']),type:z.enum(['spot','benchmark']),value:decimal,currency:z.literal('USD'),unit:z.string().min(1),periodStart:iso,periodEnd:iso,frequency:z.enum(['daily','weekly','monthly']),source}).strict()).max(8).default([]),news:z.array(z.object({id:z.string().min(1),title:z.string().min(1).max(300),publisher:z.string().min(1),url:z.string().url(),publishedAt:iso,entities:z.array(z.string().min(1)).min(1),permitted:z.literal(true),source}).strict()).max(100).default([])}).strict();
export type Replay=z.infer<typeof replaySchema>;
export function parseReplay(text:string,now=new Date().toISOString()):Replay{
 if(text.length>2000000)throw Error('Replay exceeds 2 MB');const data=replaySchema.parse(JSON.parse(text));if(Date.parse(data.asOf)>Date.parse(now))throw Error('Replay cutoff cannot be in the future');
 for(const group of [data.securities,data.crypto,data.commodities,data.news]){const ids=new Set<string>();for(const row of group){if(ids.has(row.id))throw Error('Duplicate identity');ids.add(row.id);if(Date.parse(row.source.observedAt)>Date.parse(data.asOf)||Date.parse(row.source.retrievedAt)>Date.parse(now)||Date.parse(row.source.retrievedAt)<Date.parse(row.source.observedAt))throw Error('Invalid observation/retrieval chronology');}}
 for(const s of data.securities){validateBars(s.bars);if(s.bars.some(b=>b.date>data.asOf.slice(0,10)||b.date>s.source.observedAt.slice(0,10)))throw Error('Future bar exceeds source or replay cutoff');}
 const chains={bitcoin:'Bitcoin',ethereum:'Ethereum',solana:'Solana'};
 for(const c of data.crypto){if(c.chain!==chains[c.id])throw Error('Native-chain identity mismatch');if(c.coverage==='venue'&&(!c.venue||c.marketCapUsd!==null))throw Error('Venue coverage requires venue identity and cannot inherit aggregate market cap');if(c.coverage==='aggregate'&&c.venue!==null)throw Error('Aggregate cannot impersonate venue coverage');}
 const units:Record<string,string>={gold:'USD/troy ounce',silver:'USD/troy ounce',wti:'USD/barrel',brent:'USD/barrel','natural-gas':'USD/million Btu'};
 for(const c of data.commodities){if(units[c.id]&&c.unit!==units[c.id])throw Error('Commodity unit mismatch');if(Date.parse(c.periodStart)>Date.parse(c.periodEnd)||Date.parse(c.periodEnd)>Date.parse(c.source.observedAt))throw Error('Invalid commodity observation period');}
 for(const n of data.news){if(!safeLink(n.url)||Date.parse(n.publishedAt)>Date.parse(data.asOf)||!n.entities.every(id=>['us-aapl','us-spy','bitcoin','ethereum','solana',...Object.keys(units),'copper','corn','wheat','broad-market'].includes(id)))throw Error('News URL, time or verified entity invalid');}
 return data;
}
export function replayNews(data:Replay,assetId?:string){return selectNews(data.news,data.asOf,assetId);}
